### ISSUE TITLE
h264 not working on firefox 99+

### ISSUE THREAD

**Issue by HE7086** [elFarto/nvidia-vaapi-driver#70]
firefox version: `firefox developer edition 99.0b8`
system info: 
```
System:
  Kernel: 5.16.16-zen1-1-zen arch: x86_64 bits: 64 compiler: gcc v: 11.2.0
    Desktop: KDE Plasma v: 5.24.3 Distro: Arch Linux
Graphics:
  Device-1: NVIDIA GA102 [GeForce RTX 3080 Ti] driver: nvidia v: 510.54
  Display: x11 server: X.Org v: 1.21.1.3 driver: X: loaded: nvidia
    unloaded: modesetting gpu: nvidia,nvidia-nvswitch
    resolution: 3840x2160~60Hz
  OpenGL: renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
    v: 4.6.0 NVIDIA 510.54
```

All the flags/env are correctly configured and firefox works fine playing vp9/av1 videos, only videos using h.264 codec won't play. The playback fails straight, YT gives an error screen (An error occurred. Please try again later.) without showing any content of the video.

mpv works fine with all the codecs though.
Having tested with regular firefox 98, videos paly just fine.
On firefox nightly (100.0a1) the bug also exists, so I assmue this only happens with firefox 99+ with h264.

[log](https://github.com/elFarto/nvidia-vaapi-driver/files/8364748/h264.log) playing h.264 video.

[log](https://github.com/elFarto/nvidia-vaapi-driver/files/8364692/av1.log) playing av1 video, for comparison.

To reproduce it, play any YT video while blocking other codecs using plugins like h264ify. Have tested with Twitch streams which also use h.264, also failed to play.
